include:
  - project: "gopay_infra/docker/cx-releaser"
    ref: v1.3.0
    file: "/templates/.semantic-release-ci.yml"

variables:
  REGISTRY: asia.gcr.io/gopay-systems
  CX_RELEASER_VERSION: latest

stages:
  - unit-test
  - pre-release
  - release

unit-test:
  image: golang:1.16
  services:
    - postgres:12.2-alpine
  variables:
    GOPRIVATE: source.golabs.io
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  stage: unit-test
  before_script:
    - echo $GITCONFIG | base64 --decode > ~/.gitconfig
  script:
    - cp .env.itest .env
    - make dev-install
    - make migrate
    - make test
    - make itest
  artifacts:
    reports:
      cobertura: coverage/coverage.xml
  tags:
    - i-go-gp-docker

pre-release:
  stage: pre-release
  extends: .semantic-release-pre-release
  needs:
    - unit-test
  only:
    - master
  tags:
    - i-go-gp-docker

release:
  stage: release
  extends: .semantic-release-release
  needs:
    - pre-release
  only:
    - master
  tags:
    - i-go-gp-docker
