include:
  - project: "gopay_infra/docker/cx-releaser"
    ref: v1.3.0
    file: "/templates/.semantic-release-ci.yml"

variables:
  REGISTRY: asia.gcr.io/gopay-systems
  CX_RELEASER_VERSION: latest

stages:
  - unit-test
  - pre-release
  - release
  - artefact-build
  - staging-deploy

unit-test:
  image: golang:1.16
  services:
    - postgres:12.2-alpine
  variables:
    GOPRIVATE: source.golabs.io
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  stage: unit-test
  before_script:
    - echo $GITCONFIG | base64 --decode > ~/.gitconfig
  script:
    - cp .env.itest .env
    - make dev-install
    - make migrate
    - make test
    - make itest
  artifacts:
    reports:
      cobertura: coverage/coverage.xml
  tags:
    - i-go-gp-docker

pre-release:
  stage: pre-release
  extends: .semantic-release-pre-release
  needs:
    - unit-test
  only:
    - master
  tags:
    - i-go-gp-docker

release:
  stage: release
  extends: .semantic-release-release
  needs:
    - pre-release
  only:
    - master
  tags:
    - i-go-gp-docker

artefact-build:package:
  image: asia.gcr.io/gopay-systems/cx-gopay-packager:latest
  stage: artefact-build
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - packager
  tags:
    - i-go-gp-docker

release:binary:
  image:
    name: goreleaser/goreleaser
    entrypoint: [ '' ]
  variables:
    GOPRIVATE: source.golabs.io
  stage: artefact-build
  before_script:
    - echo $GITCONFIG | base64 -d > ~/.gitconfig
  script:
    - goreleaser release --rm-dist
  only:
    - tags
  tags:
    - i-go-gp-docker

stg:deploy:
  image: asia.gcr.io/gopay-systems/gopay-cd:latest
  stage: "staging-deploy"
  script:
    - gopay-cd render scp-dependency-manager
      --dest-cluster staging-gopay-systems-01
      --namespace scp
      --team-name gopay-systems
      --chart-name chartmuseum-incubator/gopay-cron
      --chart-version 0.3.0
      --values _deployments/values/app.yml
      --values _deployments/values/app-stg.yml
      --set cron.image.tag=${CI_COMMIT_SHORT_SHA}
      --app-config scp-dependency-manager/latest/staging
    - gopay-cd deploy scp-dependency-manager --team-name gopay-systems --dest-cluster staging-gopay-systems-01 --timeout 600
  needs:
    - artefact-build:package
  tags:
    - i-go-gp-docker
  only:
    - master
