// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SlackNotificationService is an autogenerated mock type for the SlackNotificationService type
type SlackNotificationService struct {
	mock.Mock
}

// NotifyMerge provides a mock function with given fields: channelId, mergeRequestURL, repositoryName, packageName
func (_m *SlackNotificationService) NotifyMerge(channelId string, mergeRequestURL string, repositoryName string, packageName string) error {
	ret := _m.Called(channelId, mergeRequestURL, repositoryName, packageName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(channelId, mergeRequestURL, repositoryName, packageName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
